"""Refs: P1-schema R8 R9 D4 D5 S3.1 -- 스키마 v2 SQLAlchemy 모델 9개.

이 모듈이 스키마의 진실의 원천이다(01-plan 결정 1). U3 의 Alembic revision 은
이 모델을 `--autogenerate` 로 초안화한 뒤 손으로 보정한다.

컬럼 집합은 `docs/wiki/specs/S3.1-schema-v2.md` 와 글자 그대로 대응한다.
임의 컬럼(`status`, `users`, 인물-인물 관계 테이블, `person_embeddings`)을
추가하지 않는다(D5 R9, 원칙7).

## NOT NULL 정책 (F-08e812 결정)

01-plan 114행은 타임스탬프 계열(`occurred_at`/`scheduled_at` NOT NULL,
`briefed_at`/`confirmed_at`/`answer`/`answered_at`/`embedding` nullable)만
명시했고 그 밖의 문자열·JSONB·숫자 컬럼은 S3.1 에도 계획에도 명시가 없었다.
이 구현에서 다음 규칙으로 확정한다:

  - **식별자·FK·툴 시그니처(S3.2)의 필수 인자에 대응하는 컬럼은 NOT NULL.**
    `add_event(person_id, type, content, occurred_at, raw_utterance)`,
    `add_schedule(person_id, title, scheduled_at)`,
    `ask_user(kind, question, options, context)` 등 툴이 호출 시점에 반드시
    값을 채우는 컬럼은 스키마에서도 NOT NULL 로 강제해 잘못된 호출을 DB
    제약으로 조기에 잡는다. 여기 해당하는 컬럼: `user_id, display_name,
    relation_tag, hierarchy, person_id, alias, source, key, value,
    confidence, type, content, raw_utterance, occurred_at, title,
    scheduled_at, session_id, kind, question, options, context, endpoint,
    keys, step, tool_name, input, output, tokens_in, tokens_out,
    created_at, updated_at`.
  - **나중에(비동기로) 채워지는 컬럼만 nullable.** 별칭 확정 전에는 임베딩이
    없고(`embedding`), 별칭이 아직 검증 전이면(`confirmed_at`), 일정은
    브리핑 전이면(`briefed_at`), 질문은 답변 전이면(`answer`,
    `answered_at`) 값이 없는 것이 정상 상태이다. nullable 집합은 정확히
    `{embedding, confirmed_at, briefed_at, answer, answered_at}`.

`pending_questions.status` 컬럼은 만들지 않는다(S3.1 에 없음, 미결 항목).
S3.2 의 `{question_id, status:"pending"}` 은 `answered_at IS NULL` 에서
애플리케이션이 파생시키는 값이다.
"""

from __future__ import annotations

from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    DateTime,
    Double,
    ForeignKey,
    Identity,
    Index,
    Integer,
    PrimaryKeyConstraint,
    Text,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base

# 값 집합 -- CHECK 제약과 테스트가 같은 출처를 쓴다(P2 도 여기서 import).
EVENT_TYPES = (
    "conflict",
    "praise",
    "meal",
    "meeting",
    "personal_share",
    "favor",
    "other",
)
RELATION_TAGS = ("가족", "연인", "친구", "직장", "지인")
HIERARCHIES = ("상", "동", "하")
QUESTION_KINDS = ("identity", "new_person", "schedule")

# P2-tools 결정5 -- person_aliases.source 값 집합. 앱 검증만(DB CHECK 없음):
# 값 집합이 P3-er(별칭 확정 경로)·P6(승격)에서 흔들릴 가능성이 남아 있고,
# 새 Alembic revision 을 만들지 않는 것이 P2-tools 패키지 목표이기 때문이다
# (굳어지면 P3-er 의 벡터 인덱스 revision 에 CHECK 를 함께 얹는다).
ALIAS_SOURCES = ("user_said", "confirmed", "system")


def _pk() -> Mapped[int]:
    """BIGINT GENERATED BY DEFAULT AS IDENTITY 기본키."""
    return mapped_column(BigInteger, Identity(always=False), primary_key=True)


class Person(Base):
    __tablename__ = "persons"
    __table_args__ = (
        CheckConstraint(
            "relation_tag IN ('가족', '연인', '친구', '직장', '지인')",
            name="relation_tag_valid",
        ),
        CheckConstraint(
            "hierarchy IN ('상', '동', '하')",
            name="hierarchy_valid",
        ),
        Index("ix_persons_user_id", "user_id"),
    )

    id: Mapped[int] = _pk()
    user_id: Mapped[str] = mapped_column(Text, nullable=False)
    display_name: Mapped[str] = mapped_column(Text, nullable=False)
    relation_tag: Mapped[str] = mapped_column(Text, nullable=False)
    hierarchy: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[object] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[object] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


class PersonAlias(Base):
    __tablename__ = "person_aliases"
    __table_args__ = (
        Index("ix_person_aliases_person_id", "person_id"),
        Index("ix_person_aliases_alias", "alias"),
    )

    id: Mapped[int] = _pk()
    person_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("persons.id", ondelete="CASCADE"), nullable=False
    )
    alias: Mapped[str] = mapped_column(Text, nullable=False)
    source: Mapped[str] = mapped_column(Text, nullable=False)
    embedding: Mapped[object | None] = mapped_column(Vector(1536), nullable=True)
    confirmed_at: Mapped[object | None] = mapped_column(DateTime(timezone=True), nullable=True)


class PersonFact(Base):
    __tablename__ = "person_facts"
    __table_args__ = (Index("ix_person_facts_person_id_key", "person_id", "key"),)

    id: Mapped[int] = _pk()
    person_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("persons.id", ondelete="CASCADE"), nullable=False
    )
    key: Mapped[str] = mapped_column(Text, nullable=False)
    value: Mapped[str] = mapped_column(Text, nullable=False)
    confidence: Mapped[float] = mapped_column(Double, nullable=False)
    updated_at: Mapped[object] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


class FactSource(Base):
    """대리키 없음 -- 복합 기본키 (fact_id, event_id)."""

    __tablename__ = "fact_sources"
    __table_args__ = (
        PrimaryKeyConstraint("fact_id", "event_id"),
        Index("ix_fact_sources_event_id", "event_id"),
    )

    fact_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("person_facts.id", ondelete="CASCADE"), nullable=False
    )
    event_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("events.id", ondelete="CASCADE"), nullable=False
    )


class Event(Base):
    __tablename__ = "events"
    __table_args__ = (
        CheckConstraint(
            "type IN ('conflict', 'praise', 'meal', 'meeting', 'personal_share', "
            "'favor', 'other')",
            name="type_valid",
        ),
        Index("ix_events_person_id_occurred_at", "person_id", "occurred_at"),
    )

    id: Mapped[int] = _pk()
    person_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("persons.id", ondelete="CASCADE"), nullable=False
    )
    type: Mapped[str] = mapped_column(Text, nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    raw_utterance: Mapped[str] = mapped_column(Text, nullable=False)
    occurred_at: Mapped[object] = mapped_column(DateTime(timezone=True), nullable=False)
    created_at: Mapped[object] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class Schedule(Base):
    __tablename__ = "schedules"
    __table_args__ = (Index("ix_schedules_scheduled_at", "scheduled_at"),)

    id: Mapped[int] = _pk()
    person_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("persons.id", ondelete="CASCADE"), nullable=False
    )
    title: Mapped[str] = mapped_column(Text, nullable=False)
    scheduled_at: Mapped[object] = mapped_column(DateTime(timezone=True), nullable=False)
    briefed_at: Mapped[object | None] = mapped_column(DateTime(timezone=True), nullable=True)


class PendingQuestion(Base):
    __tablename__ = "pending_questions"
    __table_args__ = (
        CheckConstraint(
            "kind IN ('identity', 'new_person', 'schedule')",
            name="kind_valid",
        ),
        Index("ix_pending_questions_session_id_created_at", "session_id", "created_at"),
        Index(
            "ix_pending_questions_session_id_unanswered",
            "session_id",
            postgresql_where=text("answered_at IS NULL"),
        ),
    )

    id: Mapped[int] = _pk()
    session_id: Mapped[str] = mapped_column(Text, nullable=False)
    kind: Mapped[str] = mapped_column(Text, nullable=False)
    question: Mapped[str] = mapped_column(Text, nullable=False)
    options: Mapped[object] = mapped_column(JSONB, nullable=False)
    context: Mapped[object] = mapped_column(JSONB, nullable=False)
    answer: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[object] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    answered_at: Mapped[object | None] = mapped_column(DateTime(timezone=True), nullable=True)


class PushSubscription(Base):
    __tablename__ = "push_subscriptions"

    id: Mapped[int] = _pk()
    user_id: Mapped[str] = mapped_column(Text, nullable=False)
    endpoint: Mapped[str] = mapped_column(Text, nullable=False)
    keys: Mapped[object] = mapped_column(JSONB, nullable=False)
    created_at: Mapped[object] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class AgentTrace(Base):
    __tablename__ = "agent_traces"
    __table_args__ = (Index("ix_agent_traces_session_id_created_at", "session_id", "created_at"),)

    id: Mapped[int] = _pk()
    session_id: Mapped[str] = mapped_column(Text, nullable=False)
    step: Mapped[str] = mapped_column(Text, nullable=False)
    tool_name: Mapped[str] = mapped_column(Text, nullable=False)
    input: Mapped[object] = mapped_column(JSONB, nullable=False)
    output: Mapped[object] = mapped_column(JSONB, nullable=False)
    tokens_in: Mapped[int] = mapped_column(Integer, nullable=False)
    tokens_out: Mapped[int] = mapped_column(Integer, nullable=False)
    created_at: Mapped[object] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
