"""Refs: P5-loop S3.4 원칙9 -- app/agent 패키지 재export 진입점.

U1 시점에는 `app/agent/types.py` 의 계약 타입·trace 어휘만 있었다(01-plan
U1 "코드가 도는 건 아직 없다"). U2 가 인식 단계(`app/agent/propose.py`)를
더했고, U3 가 게이트(`app/agent/gate.py`)를 더한다 -- `run_turn`/
`resume_turn`(U4 `app/agent/loop.py`)은 아직 없으므로 그 이름은 미리
import 하지 않는다(ImportError 방지).
"""

from __future__ import annotations

from app.agent.gate import (
    GATE_REJECTION_REASONS,
    INJECTED_ARGS,
    NOT_CALLABLE_BY_LLM,
    REASON_BAD_ARGS,
    REASON_LIMIT,
    REASON_NEEDS_CONFIRMATION,
    REASON_NOT_CALLABLE_BY_LLM,
    REASON_PERSON_ID_FROM_LLM,
    REASON_UNKNOWN_TOOL,
    GateConfig,
    check,
)
from app.agent.propose import (
    PROPOSAL_ARG_SCHEMA,
    PROPOSAL_SCHEMA,
    PROPOSAL_TOOL_NAME,
    PROPOSERS,
    ClaudeProposer,
    FakeProposer,
    GeminiProposer,
    OpenAIProposer,
    Proposer,
    build_propose_prompt,
    proposer_from_env,
    validate_proposal,
)
from app.agent.types import (
    BUCKET_EXECUTE,
    BUCKET_HINT_ONLY,
    GATE_BUCKETS,
    LOOP_RESUME_VERSION,
    LOOP_TRACE_STEPS,
    LOOP_TRACE_TOOL_NAME,
    NEW_PERSON_TAG_OPTIONS,
    STEP_LOOP_ERROR,
    STEP_LOOP_EXTRACT,
    STEP_LOOP_GATE,
    STEP_LOOP_RECORD,
    STEP_LOOP_RESOLVE_DONE,
    STEP_LOOP_RESUME,
    STEP_LOOP_TURN,
    AcceptedProposal,
    EventDraft,
    GateLimits,
    GateVerdict,
    LoopError,
    PendingCall,
    PendingResume,
    Proposal,
    RejectedProposal,
    ResumeContextError,
    ResumeInput,
    ScheduleDraft,
    ScheduleResumeRef,
    StoredSummary,
    ToolCallProposal,
    TurnResult,
)

__all__ = [
    "GATE_REJECTION_REASONS",
    "INJECTED_ARGS",
    "NOT_CALLABLE_BY_LLM",
    "REASON_BAD_ARGS",
    "REASON_LIMIT",
    "REASON_NEEDS_CONFIRMATION",
    "REASON_NOT_CALLABLE_BY_LLM",
    "REASON_PERSON_ID_FROM_LLM",
    "REASON_UNKNOWN_TOOL",
    "GateConfig",
    "check",
    "PROPOSAL_ARG_SCHEMA",
    "PROPOSAL_SCHEMA",
    "PROPOSAL_TOOL_NAME",
    "PROPOSERS",
    "ClaudeProposer",
    "FakeProposer",
    "GeminiProposer",
    "OpenAIProposer",
    "Proposer",
    "build_propose_prompt",
    "proposer_from_env",
    "validate_proposal",
    "BUCKET_EXECUTE",
    "BUCKET_HINT_ONLY",
    "GATE_BUCKETS",
    "LOOP_RESUME_VERSION",
    "LOOP_TRACE_STEPS",
    "LOOP_TRACE_TOOL_NAME",
    "NEW_PERSON_TAG_OPTIONS",
    "STEP_LOOP_ERROR",
    "STEP_LOOP_EXTRACT",
    "STEP_LOOP_GATE",
    "STEP_LOOP_RECORD",
    "STEP_LOOP_RESOLVE_DONE",
    "STEP_LOOP_RESUME",
    "STEP_LOOP_TURN",
    "AcceptedProposal",
    "EventDraft",
    "GateLimits",
    "GateVerdict",
    "LoopError",
    "PendingCall",
    "PendingResume",
    "Proposal",
    "RejectedProposal",
    "ResumeContextError",
    "ResumeInput",
    "ScheduleDraft",
    "ScheduleResumeRef",
    "StoredSummary",
    "ToolCallProposal",
    "TurnResult",
]
