"""Refs: P1-schema S3.1, P2-tools 결정8 -- 저장소 루트 sys.path 등록 + 공용 픽스처.

`app` 패키지 임포트를 위한 `sys.path.insert` 는 P1-schema 부터 있던 것을
그대로 유지한다(U1 은 그 아래에 픽스처만 추가한다).

## 실 DB + 롤백 픽스처 (결정8 -- SQLite 불가)

`JSONB`·`vector(1536)`·부분 인덱스·`BIGINT GENERATED BY DEFAULT AS IDENTITY`
가 SQLite 에는 없거나 다르게 동작하므로, DB 를 쓰는 테스트는 로컬
PostgreSQL(기본 포트 5433, `POSTGRES_PORT` 로 지정)에 실제로 붙는다.

- `db_engine`(세션 스코프): 접속을 확인하고, 실패하면 `pytest.skip` 한다 --
  `-rs` 로 skip 사유가 그대로 보인다("local PostgreSQL not reachable").
- `db_session`(함수 스코프): 커넥션 위에 바깥 트랜잭션을 열고, 그 커넥션에
  `join_transaction_mode="create_savepoint"` 로 세션을 바인딩한다. 테스트가
  `flush()`·`commit()` 을 호출해도 `commit()` 은 SAVEPOINT 만 커밋하므로
  바깥 트랜잭션은 살아 있고, 픽스처가 끝나면 그 바깥 트랜잭션을 rollback 해
  DB 에 아무 것도 남기지 않는다.

`dbtest` 마커는 `pytest_configure` 에서 등록만 한다 -- **autouse 로 두지
않는다**. `db_engine`/`db_session` 을 실제로 의존하는 테스트만 그 마커가
붙어야 skip 사유가 정확하게 나온다(마커만 붙이고 픽스처를 안 쓰면 DB 없이도
돈다는 오해를 만든다).
"""

from __future__ import annotations

import hashlib
import random
import sys
from collections.abc import Callable, Iterator
from pathlib import Path

import pytest
from sqlalchemy import Engine, text
from sqlalchemy.orm import Session

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.db.session import get_engine  # noqa: E402
from app.embedding import EMBEDDING_DIM  # noqa: E402


def pytest_configure(config: pytest.Config) -> None:
    config.addinivalue_line(
        "markers",
        "dbtest: 실 PostgreSQL(로컬, POSTGRES_PORT 기본 5433) 접속이 필요한 테스트",
    )


@pytest.fixture(scope="session")
def db_engine() -> Engine:
    """실 PostgreSQL 접속을 확인한다. 실패하면 skip(사유가 -rs 에 보인다)."""
    engine = get_engine()
    try:
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
    except Exception as exc:  # noqa: BLE001 -- 접속 실패를 전부 skip 으로 통일
        pytest.skip(
            "local PostgreSQL not reachable — set POSTGRES_PORT=5433 "
            f"({type(exc).__name__}: {exc})"
        )
    return engine


@pytest.fixture()
def db_session(db_engine: Engine) -> Iterator[Session]:
    """바깥 트랜잭션 + SAVEPOINT 로 격리된 세션. 끝나면 항상 rollback."""
    connection = db_engine.connect()
    outer_transaction = connection.begin()
    session = Session(bind=connection, join_transaction_mode="create_savepoint")
    try:
        yield session
    finally:
        session.close()
        outer_transaction.rollback()
        connection.close()


def _deterministic_vector(value: str, dimension: int = 1536) -> list[float]:
    """문자열 → 결정적 단위벡터(1536차원). 같은 문자열은 항상 같은 벡터.

    `hashlib.sha256` 으로 시드를 뽑아 `random.Random` 을 초기화하므로 실행
    환경·프로세스와 무관하게 재현된다(원칙8). 정규화(단위 벡터)해 코사인
    유사도 계산이 실제 임베딩과 같은 스케일로 동작한다.
    """
    seed = int.from_bytes(hashlib.sha256(value.encode("utf-8")).digest()[:8], "big")
    rng = random.Random(seed)
    raw = [rng.uniform(-1.0, 1.0) for _ in range(dimension)]
    norm = sum(v * v for v in raw) ** 0.5 or 1.0
    return [v / norm for v in raw]


@pytest.fixture()
def fake_embedder() -> Callable[[list[str]], list[list[float]]]:
    """결정적 가짜 임베딩 콜러블. `EmbeddingProvider.embed(texts)` 와 같은 형태
    (`list[str] -> list[list[float]]`) -- U3 가 `app.embedding.EmbeddingProvider`
    를 정의하면 이 픽스처를 그 자리에 주입한다. U1 은 픽스처만 둔다.

    이 픽스처는 문자열마다 **독립적인** 무작위 단위벡터를 만들므로 서로
    다른 문자열은 항상 거의 직교한다("팀장"과 "부장님"이 직교해 승진
    케이스를 만들 수 없다) -- 그룹 안에서 목표 유사도를 갖는 벡터가
    필요하면 `grouped_embedder` 를 쓴다(결정9, P3-er U7).
    """

    def _embed(texts: list[str]) -> list[list[float]]:
        return [_deterministic_vector(t) for t in texts]

    return _embed


def _grouped_vector_for_seed(key: str, *, dimension: int, seed: int) -> list[float]:
    """`key`(그룹 베이스/잡음/미등재 문자열을 구분하는 합성 문자열)로부터
    결정적 단위벡터를 만든다. `_deterministic_vector` 와 같은 방식(sha256
    → `random.Random` 시드)이지만 `seed` 를 문자열에 섞어 팩토리 호출마다
    (기본값이 아닌 `seed` 를 주면) 다른 벡터 공간을 쓸 수 있게 한다."""

    return _deterministic_vector(f"{seed}:{key}", dimension)


@pytest.fixture()
def grouped_embedder() -> Callable[..., Callable[[list[str]], list[list[float]]]]:
    """그룹 기반 결정적 가짜 임베딩 **팩토리**(결정9, P3-er U7 -- 승진
    회귀 "팀장 → 부장님"처럼 서로 다른 문자열이 같은 인물을 가리켜야
    유사도가 높아야 하는 케이스를 `fake_embedder`(문자열마다 독립 벡터)로는
    만들 수 없다).

    `grouped_embedder(groups, *, within=0.85, dim=EMBEDDING_DIM, seed=0)`
    을 호출하면 `EmbeddingProvider.embed(texts)` 와 같은 콜러블을 돌려준다:

    - `groups` = `{그룹이름: [문자열, ...]}`. 같은 그룹에 속한 문자열끼리는
      코사인 유사도가 `within` 근처(±0.05)가 되도록 만든다 -- 그룹마다
      결정적 "베이스" 단위벡터를 하나 뽑고, 각 문자열은
      `sqrt(within)*베이스 + sqrt(1-within)*문자열별 잡음벡터` 를 다시
      정규화해 만든다. 고차원(`EMBEDDING_DIM=1536`)에서 서로 다른 잡음
      벡터끼리, 그리고 잡음과 베이스끼리는 거의 직교하므로, 두 벡터의
      내적은 `within` 근처로 수렴하고 베이스·잡음 성분이 상쇄돼 노름도
      거의 1로 유지된다(단위벡터에 가깝다).
    - `groups` 에 없는 문자열("미등재")은 그 문자열만으로 시드를 뽑은
      독립 단위벡터가 된다 -- 등재된 벡터들과 거의 직교(코사인 ≈0)한다.
    - 결정적이다: 같은 `groups`/`within`/`dim`/`seed` 로 다시 호출하면
      (그리고 프로세스가 달라져도) 항상 같은 벡터가 나온다(`hashlib.sha256`
      기반 시드, 원칙8 재현성) -- `random`/시각 등 비결정 요소를 쓰지
      않는다.
    - 반환 벡터는 항상 단위벡터(노름 ≈1)이고 차원은 `dim`.

    승진 회귀(01-plan 결정9 "승진 회귀(a) 픽스처 확정")가 이 픽스처로
    `"팀장"`·`"김팀장"`·`"부장님"` 을 한 그룹에 묶어 `s_emb ≈ 0.85` 를
    만든다.
    """

    def _factory(
        groups: dict[str, list[str]],
        *,
        within: float = 0.85,
        dim: int = EMBEDDING_DIM,
        seed: int = 0,
    ) -> Callable[[list[str]], list[list[float]]]:
        string_to_group: dict[str, str] = {}
        for group_name, members in groups.items():
            for member in members:
                string_to_group[member] = group_name

        base_weight = within**0.5
        noise_weight = max(0.0, 1.0 - within) ** 0.5

        def _base_vector(group_name: str) -> list[float]:
            return _grouped_vector_for_seed(
                f"__group_base__:{group_name}", dimension=dim, seed=seed
            )

        def _embed(texts: list[str]) -> list[list[float]]:
            vectors: list[list[float]] = []
            for text in texts:
                group_name = string_to_group.get(text)
                if group_name is None:
                    vectors.append(
                        _grouped_vector_for_seed(
                            f"__unregistered__:{text}", dimension=dim, seed=seed
                        )
                    )
                    continue
                base = _base_vector(group_name)
                noise = _grouped_vector_for_seed(
                    f"__noise__:{group_name}:{text}", dimension=dim, seed=seed
                )
                combined = [
                    base_weight * b + noise_weight * n for b, n in zip(base, noise)
                ]
                norm = sum(v * v for v in combined) ** 0.5 or 1.0
                vectors.append([v / norm for v in combined])
            return vectors

        return _embed

    return _factory
